name: Line Bot Daily Job

on:
  schedule:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5  # ตรงนี้ต้องมีคำว่า actions/ นำหน้าครับ
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests gspread oauth2client feedparser beautifulsoup4
        
      - name: Run Bot Script
        env:
          LINE_ACCESS_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
          MY_USER_ID: ${{ secrets.MY_USER_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: python bot/main.py
